package com.example.reloop.activities; // Suggested move from .activities to .models

import com.google.firebase.database.IgnoreExtraProperties;
import java.io.Serializable;

/**
 * Data model representing a product in the Reloop marketplace.
 * Implements Serializable to allow passing product objects between Fragments and Activities.
 */
@IgnoreExtraProperties
public class product implements Serializable {

    // --- Identification Fields ---
    public String pid;          // Unique Product ID (generated by Firebase push())
    public String sellerId;     // UID of the user who posted the item

    // --- Content Fields ---
    public String title;        // Name of the product
    public String description;  // Detailed item description
    public String imageUrl;     // Download URL from Firebase Storage

    // --- Classification & Pricing ---
    public String price;        // Selling price (stored as String for flexibility)
    public String category;     // Category (e.g., Electronics, Books, Furniture)

    // --- Status & Metadata ---
    public long timestamp;      // Post creation time (Unix timestamp)
    public boolean isSold;      // Transaction status (true if the item is no longer available)

    /**
     * Default constructor required for Firebase Realtime Database.
     * Necessary for DataSnapshot.getValue(Product.class)
     */
    public product() {
        // Required empty constructor
    }

    /**
     * Convenience constructor for creating a new product listing.
     * Initializes timestamp and sets default sold status to false.
     */
    public product(String pid, String title, String description, String price,
                   String category, String imageUrl, String sellerId) {
        this.pid = pid;
        this.title = title;
        this.description = description;
        this.price = price;
        this.category = category;
        this.imageUrl = imageUrl;
        this.sellerId = sellerId;
        this.timestamp = System.currentTimeMillis();
        this.isSold = false;
    }
}