package com.example.reloop.models;

import com.google.firebase.database.IgnoreExtraProperties;
import java.io.Serializable;

/**
 * Core product model for the marketplace.
 * Member A: Updated this on March 24th to support serialization.
 */
@IgnoreExtraProperties
public class product implements Serializable {

    public String pid;          // Unique ID generated by Firebase push().getKey()
    public String sellerId;     // Owner of this item
    public String title;
    public String description;
    public String imageUrl;
    public String price;
    public String category;     // e.g. Electronics, Furniture
    public long timestamp;
    public boolean isSold;      // Track if item is still available

    // Default constructor for Firebase DataSnapshot
    public product() {
    }

    // For creating new listings in PostProductFragment
    public product(String pid, String title, String description, String price,
                   String category, String imageUrl, String sellerId) {
        this.pid = pid;
        this.title = title;
        this.description = description;
        this.price = price;
        this.category = category;
        this.imageUrl = imageUrl;
        this.sellerId = sellerId;
        this.timestamp = System.currentTimeMillis();
        this.isSold = false;
    }
}
