package com.example.reloop.shared.views;

import android.content.Context;
import android.util.AttributeSet;
import android.view.LayoutInflater;
import android.widget.FrameLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
// This class will be auto-generated by Android Studio after Rebuild Project
import com.example.reloop.databinding.ViewLoadingButtonBinding;

/**
 * Custom button with loading state functionality.
 * Shows a progress indicator when loading and prevents duplicate clicks.
 */
@SuppressWarnings("unused")
public class LoadingButton extends FrameLayout {

    private ViewLoadingButtonBinding binding;
    private String originalText;
    private boolean isLoading = false;

    public LoadingButton(@NonNull Context context) {
        super(context);
        init(context);
    }

    public LoadingButton(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        init(context);
    }

    public LoadingButton(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(context);
    }

    /**
     * Initialize the view binding and set default attributes
     */
    private void init(Context context) {
        // Inflate the layout using ViewBinding
        binding = ViewLoadingButtonBinding.inflate(LayoutInflater.from(context), this);
        setClickable(true);
        setFocusable(true);
    }

    /**
     * Set the text to be displayed on the button
     */
    public void setText(String text) {
        originalText = text;
        if (!isLoading) {
            binding.buttonText.setText(text);
        }
    }

    /**
     * Set the loading state of the button.
     * When loading, it hides the text, shows the progress bar, and disables clicking.
     */
    public void setLoading(boolean loading) {
        this.isLoading = loading;

        if (loading) {
            binding.buttonText.setText("");
            binding.progressBar.setVisibility(VISIBLE);
            setEnabled(false); // Prevent further clicks
        } else {
            binding.buttonText.setText(originalText);
            binding.progressBar.setVisibility(GONE);
            setEnabled(true); // Re-enable clicks
        }
    }

    /**
     * Check if the button is currently in a loading state
     */
    public boolean isLoading() {
        return isLoading;
    }

    /**
     * Set a custom click listener on the root element of this custom view
     */
    public void setOnButtonClickListener(OnClickListener listener) {
        binding.getRoot().setOnClickListener(listener);
    }
}